add healthcheck route for server.

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -6,7 +6,7 @@ on:
     branches: [master]
 jobs:
   test:
-    timeout-minutes: 60
+    timeout-minutes: 5
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -18,6 +18,27 @@ jobs:
       - name: setup go app
         run: |
           docker compose up -d
+      - name: wait for db to be ready
+        run: |
+          max_retries=10
+          retries=0
+          healthcheck_url="http://localhost:8091/healthcheck"
+
+          until [ $retries -ge $max_retries ]
+          do
+            status_code=$(curl -o /dev/null -s -w "%{http_code}" $healthcheck_url)
+            if [ $status_code -eq 200 ]; then
+              echo "Health check successful (HTTP 200 OK)"
+              exit 0
+            else
+              echo "Health check failed (HTTP $status_code), retrying..."
+              retries=$((retries+1))
+              sleep 10  # Adjust retry interval as needed
+            fi
+          done
+
+          echo "Health check failed after $max_retries retries"
+          exit 1
 
       - name: setup node app
         run: |
